# Generated by Django 5.2.17 on 2026-08-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(help_text='Simplified GeoJSON polygon of the loss zone')),
                ('area_hectares', models.FloatField(help_text='Surface area in hectares')),
                ('ndvi_before', models.FloatField(help_text='Mean baseline NDVI')),
                ('ndvi_after', models.FloatField(help_text='Mean monitoring NDVI')),
                ('ndvi_change', models.FloatField(help_text='Mean delta NDVI (negative)')),
                ('centroid_lat', models.FloatField()),
                ('centroid_lng', models.FloatField()),
                ('detected_date', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('requires_verification', 'Requires Field Verification'), ('verified_loss', 'Field Verified Loss'), ('false_positive', 'False Positive / Permitted Activity'), ('resolved', 'Inspection Completed')], default='requires_verification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='analysis.analysisjob')),
            ],
            options={
                'ordering': ['-area_hectares'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField()),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
            ],
        ),
    ]
