# Generated by Django 5.2.17 on 2026-08-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Confidence score of the prediction', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='predicted_class',
            field=models.CharField(blank=True, help_text='Predicted risk class from ML model', max_length=100, null=True),
        ),
    ]
