# Generated by Django 5.2.17 on 2026-08-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon/MultiPolygon coordinates')),
                ('area_sqkm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_start', models.CharField(max_length=20)),
                ('historical_end', models.CharField(max_length=20)),
                ('current_start', models.CharField(max_length=20)),
                ('current_end', models.CharField(max_length=20)),
                ('threshold', models.FloatField(default=-0.3)),
                ('min_area_ha', models.FloatField(default=0.5)),
                ('algorithm_version', models.CharField(default='v1.0-ndvi-delta', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tile_url_template', models.TextField(blank=True, default='')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='analysis.aoi')),
            ],
        ),
    ]
